// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Student.Entity
{
    public partial class CurdContext : DbContext
    {
        public CurdContext()
        {
        }

        public CurdContext(DbContextOptions<CurdContext> options)
            : base(options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=curd");
            }
        }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<StudentRecords> StudentRecords { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Login>(entity =>
            {
                entity.HasKey(e => e.StudId);

                entity.Property(e => e.StudId).HasColumnName("Stud_id");

                entity.Property(e => e.LoginName)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("Login_name");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<StudentRecords>(entity =>
            {
                entity.HasKey(e => e.StudentId)
                    .HasName("PK_Student_");

                entity.ToTable("Student_Records");

                entity.Property(e => e.StudentId).HasColumnName("Student_Id");

                entity.Property(e => e.ChemistryMark).HasColumnName("Chemistry_Mark");

                entity.Property(e => e.ComputerMark).HasColumnName("Computer_Mark");

                entity.Property(e => e.CurrentTimeStamp)
                    .HasColumnType("date")
                    .HasColumnName("Current_time_stamp")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DateOfBirth)
                    .HasColumnType("date")
                    .HasColumnName("Date_Of_Birth");

                entity.Property(e => e.FavoriteSubject)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Favorite_Subject");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("First_Name");

                entity.Property(e => e.InterestedCourse)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Interested_Course");

                entity.Property(e => e.IsDelete).HasColumnName("Is_Delete");

                entity.Property(e => e.MathsMark).HasColumnName("Maths_Mark");

                entity.Property(e => e.SecondName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("Second_Name");

                entity.Property(e => e.UpdateTimeStamp)
                    .HasColumnType("date")
                    .HasColumnName("Update_time_stamp")
                    .HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}