// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Student.Entity
{
    public partial class Login
    {
        public int StudId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
    }
}