// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Student.Entity
{
    public partial class StudentRecords
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int Age { get; set; }
        public string FavoriteSubject { get; set; }
        public string InterestedCourse { get; set; }
        public int MathsMark { get; set; }
        public int ChemistryMark { get; set; }
        public int ComputerMark { get; set; }
        public bool IsDelete { get; set; }
        public DateTime CurrentTimeStamp { get; set; }
        public DateTime UpdateTimeStamp { get; set; }
    }
}